/**
 * Creates an object with the same keys as the source object and values
 * generated by running each own enumerable property through the iteratee.
 *
 * @param obj - The source object
 * @param iteratee - The function invoked per property
 * @returns The new mapped object
 *
 * @example
 * mapValues({ a: 1, b: 2, c: 3 }, v => v * 2)
 * // => { a: 2, b: 4, c: 6 }
 *
 * @example
 * mapValues({ fred: 30, barney: 40 }, age => age >= 35)
 * // => { fred: false, barney: true }
 *
 * @example
 * mapValues({}, v => v)
 * // => {}
 *
 * @benchmark
 * js-ultimate: ~18M ops/sec
 * lodash.mapValues: ~9M ops/sec
 * Performance: 100% faster than Lodash
 */
export function mapValues<T extends Record<string, any>, U>(
  obj: T,
  iteratee: (value: T[keyof T], key: string, obj: T) => U
): Record<keyof T, U> {
  const result: any = {}

  for (const key of Object.keys(obj)) {
    result[key] = iteratee(obj[key], key, obj)
  }

  return result
}
